//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIO_MONITORING {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArduinoFormat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArduinoFormat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIO_MONITORING.ArduinoFormat", typeof(ArduinoFormat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string ArduinoSayCanLogout {
            get {
                return ResourceManager.GetString("ArduinoSayCanLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2Solenoid:OFF.
        /// </summary>
        internal static string CO2SolenoidOFF {
            get {
                return ResourceManager.GetString("CO2SolenoidOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2Solenoid:ON.
        /// </summary>
        internal static string CO2SolenoidON {
            get {
                return ResourceManager.GetString("CO2SolenoidON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooler:OFF.
        /// </summary>
        internal static string CoolerOFF {
            get {
                return ResourceManager.GetString("CoolerOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooler:ON.
        /// </summary>
        internal static string CoolerON {
            get {
                return ResourceManager.GetString("CoolerON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDGrow:OFF.
        /// </summary>
        internal static string LEDGrowOFF {
            get {
                return ResourceManager.GetString("LEDGrowOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDGrow:ON.
        /// </summary>
        internal static string LEDGrowON {
            get {
                return ResourceManager.GetString("LEDGrowON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string LevelSensorGood {
            get {
                return ResourceManager.GetString("LevelSensorGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string LevelSensorNeedFill {
            get {
                return ResourceManager.GetString("LevelSensorNeedFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay1n:OFF.
        /// </summary>
        internal static string Relay1nOFF {
            get {
                return ResourceManager.GetString("Relay1nOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay1n:ON.
        /// </summary>
        internal static string Relay1nON {
            get {
                return ResourceManager.GetString("Relay1nON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay2n:OFF.
        /// </summary>
        internal static string Relay2nOFF {
            get {
                return ResourceManager.GetString("Relay2nOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay2n:ON.
        /// </summary>
        internal static string Relay2nON {
            get {
                return ResourceManager.GetString("Relay2nON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay3n:OFF.
        /// </summary>
        internal static string Relay3nOFF {
            get {
                return ResourceManager.GetString("Relay3nOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay3n:ON.
        /// </summary>
        internal static string Relay3nON {
            get {
                return ResourceManager.GetString("Relay3nON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestSensor.
        /// </summary>
        internal static string requestSensor {
            get {
                return ResourceManager.GetString("requestSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string SlientStopToArduino {
            get {
                return ResourceManager.GetString("SlientStopToArduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVLight:OFF.
        /// </summary>
        internal static string UVLightOFF {
            get {
                return ResourceManager.GetString("UVLightOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVLight:ON.
        /// </summary>
        internal static string UVLightON {
            get {
                return ResourceManager.GetString("UVLightON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacuumPump:OFF.
        /// </summary>
        internal static string VacuumPumpOFF {
            get {
                return ResourceManager.GetString("VacuumPumpOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacuumPump:ON.
        /// </summary>
        internal static string VacuumPumpON {
            get {
                return ResourceManager.GetString("VacuumPumpON", resourceCulture);
            }
        }
    }
}
